---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vault-secrets-operator-system
spec:
  method: kubernetes
  mount: ${VAULT_K8S_AUTH_MOUNT}
  # Vault Enterprise / HCP Vault namespace (e.g. 'admin' for HCP Vault)
  # Leave empty for Vault OSS
  namespace: ${VAULT_NAMESPACE}
  kubernetes:
    role: ${VAULT_K8S_ROLE}
    serviceAccount: vso-auth-sa
    tokenExpirationSeconds: 600
  vaultConnectionRef: vault-connection
  allowedNamespaces:
    - ansible-automation-platform
    - vault-secrets-operator-system
