---
# Patch source-controller to remove fsGroup:1337 which violates OCP restricted-v2 SCC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      securityContext:
        fsGroup: null
---
# Patch notification-controller to remove fsGroup:1337
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    spec:
      securityContext:
        fsGroup: null
