---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: automation-eda-admin-password
  namespace: ansible-automation-platform
spec:
  vaultAuthRef: vault-secrets-operator-system/vault-auth
  mount: VAULT_MOUNT_PLACEHOLDER
  type: kv-v2
  path: aap/CLUSTER_NAME/credentials/aap
  refreshAfter: 1m
  destination:
    name: automation-eda-admin-password
    create: true
    transformation:
      templates:
        password:
          text: '{{- .Secrets.eda_admin_password -}}'
