---
# Source: galaxy-operator/roles/common/templates/galaxy-admin-password.secret.yaml.j2
# Key name: 'password'
# Vault path: aap/<CLUSTER_NAME>/credentials/aap
# Vault key: hub_admin_password
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: automation-hub-admin-password
  namespace: ansible-automation-platform
spec:
  vaultAuthRef: vault-secrets-operator-system/vault-auth
  mount: VAULT_MOUNT_PLACEHOLDER
  type: kv-v2
  path: aap/CLUSTER_NAME/credentials/aap
  refreshAfter: 1m
  destination:
    name: automation-hub-admin-password
    create: true
    transformation:
      templates:
        password:
          text: '{{- .Secrets.hub_admin_password -}}'
